In [1]:
# Description: This program classifies images

In [2]:
#Load the data
from keras.datasets import cifar10
(x_train, y_train), (x_test,y_test) = cifar10.load_data()

Using TensorFlow backend.


In [3]:
#Get the data types
print(type(x_train))
print(type(y_train))
print(type(x_test))
print(type(y_test))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
#Get the shape of the data
print('x_train shape:', x_train.shape)
print('y_train shape:', y_train.shape)
print('x_test shape:', x_test.shape)
print('y_test shape:', y_test.shape)

x_train shape: (50000, 32, 32, 3)
y_train shape: (50000, 1)
x_test shape: (10000, 32, 32, 3)
y_test shape: (10000, 1)


In [5]:
#Take a look at the first image in the training data set
x_train[0]

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [6]:
#Show the image as a picture
import matplotlib.pyplot as plt
img = plt.imshow(x_train[0])

In [7]:
#Print the label of the first image of the training data set
print('The label is:', y_train[0])

The label is: [6]


In [8]:
#One Hot Encoding: Convert the labels into a set of 10 numbers to input into the neural network
from keras.utils import to_categorical
y_train_one_hot = to_categorical(y_train)
y_test_one_hot = to_categorical(y_test)

# print the new labels in the training data set
print(y_train_one_hot)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [9]:
#Normalize the pixels in the images  to be values between 0 and 1
x_train = x_train / 255
x_test = x_test /255

In [10]:
#Build the CNN
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D

#Create the architecture
model = Sequential()

#Convolution layer to extract features from input image
model.add(Conv2D(32, (5,5), activation='relu', input_shape=(32,32,3)))

#Pooling layer
model.add(MaxPooling2D(pool_size=(2,2)))

#Convolution layer to extract features from input image
model.add(Conv2D(32, (5,5), activation='relu'))

#Pooling layer
model.add(MaxPooling2D(pool_size=(2,2)))

#Flatten the image layer
model.add(Flatten())

model.add(Dense(1000, activation='relu'))
model.add(Dense(10, activation='softmax'))



In [11]:
#Compile the model
model.compile(
    loss='categorical_crossentropy',
    optimizer = 'adam',
    metrics =['accuracy']
)

In [ ]:
#Train the model
hist = model.fit(x_train, y_train_one_hot, batch_size=256, epochs=10, validation_split=0.3)

Train on 35000 samples, validate on 15000 samples
Epoch 1/10
35000/35000 [==============================] - 36s 1ms/step - loss: 1.6860 - accuracy: 0.3881 - val_loss: 1.4245 - val_accuracy: 0.4874
Epoch 2/10
35000/35000 [==============================] - 35s 1ms/step - loss: 1.3503 - accuracy: 0.5159 - val_loss: 1.3466 - val_accuracy: 0.5156
Epoch 3/10
35000/35000 [==============================] - 36s 1ms/step - loss: 1.2132 - accuracy: 0.5696 - val_loss: 1.2077 - val_accuracy: 0.5739
Epoch 4/10
35000/35000 [==============================] - 36s 1ms/step - loss: 1.1053 - accuracy: 0.6082 - val_loss: 1.1426 - val_accuracy: 0.6019
Epoch 5/10
35000/35000 [==============================] - 36s 1ms/step - loss: 1.0165 - accuracy: 0.6413 - val_loss: 1.0567 - val_accuracy: 0.6314
Epoch 6/10
35000/35000 [==============================] - 34s 982us/step - loss: 0.9531 - accuracy: 0.6662 - val_loss: 1.0213 - val_accuracy: 0.6434
Epoch 7/10
35000/35000 [==============================] - 36s 1ms/

In [ ]:
#Evaluate the model
model.evaluate(x_test, y_test_one_hot)[1]

In [ ]:
#Visualize the models accuracy
plt.plot(hist.history['accuracy'])
plt.plot(hist.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Val'], loc='upper left')
plt.show()

In [ ]:
#Visualize the models accuracy
plt.plot(hist.history['loss'])
plt.plot(hist.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Val'], loc='upper right')
plt.show()

In [ ]:
#Load data to make classifications

my_image = plt.imread('cat.jpg')

In [ ]:
#Show the uploaded image
img = plt.imshow(my_image)

In [ ]:
#Resize the image
from skimage.transform import resize
my_image_resized = resize(my_image, (32,32,3))
img = plt.imshow(my_image_resized)

In [ ]:
#Get the probabilities for each class
import numpy as np
probabilities = model.predict( np.array([my_image_resized,]) )
#Show the probability for each class
probabilities

In [ ]:
number_to_class = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
index = np.argsort(probabilities[0,:])

#Print the first 5 most likely classes / labels
print('Most likely class:', number_to_class[index[9]], "--Probability:", probabilities[0, index[9]])
print('Second most likely class:', number_to_class[index[8]], "--Probability:", probabilities[0, index[8]])
print('Third most likely class:', number_to_class[index[7]], "--Probability:", probabilities[0, index[7]])
print('Fourth most likely class:', number_to_class[index[6]], "--Probability:", probabilities[0, index[6]])
print('Fifth most likely class:', number_to_class[index[5]], "--Probability:", probabilities[0, index[5]])

In [ ]:
#Save the model
model.save('my_model.h5')

In [ ]:
#To load the model
from keras.models import load_model
model = load_model('my_model.h5')